config/routes.rb
Quotables::Application.routes.draw do
  resources :favorites

  devise_for :users
  resources :quotes
  root to: "quotes#index"

  

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :quote
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  validates :content, :author, uniqueness: true
  def next
    quote = Quote.where("id > ?", id).order("id ASC").first
    quote ? quote : Quote.first
  end

  def prev
    quote = Quote.where("id < ?", id).order("id DESC").first
    quote ? quote : Quote.last
  end

  def generate_next(direction)
    if direction == 'next' 
      @quote = Quote.find(self.next.id)
    elsif direction == 'previous'
      @quote = Quote.find(self.prev.id)
    end
    @quote || self
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  validates :email, uniqueness: true
  has_many :favorites

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!
  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to '/', notice: 'Favorite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @favorite }
      else
        format.html { render action: 'new' }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: 'Favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:quote_id, :user_id)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :only_vanessa, except: :index

  def only_vanessa
    redirect_to '/' if current_user.email != 'vanessakayez@aim.com'
  end

  def index
    @quote = params[:id].present? ? Quote.find_by_id(params[:id]) : Quote.first
    @quote = @quote.generate_next(params[:direction])
    respond_to do |format|
      format.html{@quote}
      format.json{render json: @quote}
    end
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def edit
  end

  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:content, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/favorites/_form.html.haml
= form_for @favorite do |f|
  - if @favorite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@favorite.errors.count, "error")} prohibited this favorite from being saved:"
      %ul
        - @favorite.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :quote_id
    = f.number_field :quote_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'

app/views/favorites/edit.html.haml
%h1 Editing favorite

= render 'form'

= link_to 'Show', @favorite
\|
= link_to 'Back', favorites_path

app/views/favorites/index.html.haml
%center
  %h4 Favorites
  %table
    %tr
      %th{style:'width:79%'} 
      %th
      %th

    - @favorites.each do |favorite|
      %tr
        %td= simple_format favorite.quote.content[0...15], class: 'cursive'
        %td= link_to 'Show', favorite 
        %td= link_to 'Destroy', favorite, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/favorites/new.html.haml
%h1 New favorite

= render 'form'

= link_to 'Back', favorites_path

app/views/favorites/show.html.haml
%p#notice= notice

%p
  %b Quote:
  = simple_format @favorite.quote.content, class: 'cursive'

= link_to 'Back', favorites_path

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %meta{content: "Quotables throughout time", name: "description"}/
    %meta{content: "Vanessa Zolnierowski - Dan Bickford", name: "author"}/
    %link{:href => "/assets/quotables.png", :rel => "shortcut icon"}/
    %title QUOTABLES ONLINE
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    / Bootstrap core CSS
    %link{href: "http://fonts.googleapis.com/css?family=Arizonia", rel: "stylesheet", type: "text/css"}/
    %link{href: "/css/bootstrap.css", rel: "stylesheet"}/
    / Add custom CSS here
    %link{href: "/css/stylish-portfolio.css", rel: "stylesheet"}/
    %link{href: "font-awesome/css/font-awesome.min.css", rel: "stylesheet"}/
  %body
    / Side Menu
    %a#menu-toggle.btn.btn-primary.btn-lg.toggle{href: "#"}
      %i.fa.fa-bars
    #sidebar-wrapper
      %ul.sidebar-nav
        %a#menu-close.btn.btn-default.btn-lg.pull-right.toggle{href: "#"}
          %i.fa.fa-times
        %li.sidebar-brand
          - if current_user
            %a{href: "/"}= current_user.email[0...16] 
          - else
            %a{href: "/"} Quotables Online
        %li
          %a{href: "/quotes"} Quotes
        - if current_user
          - if current_user.email == 'vanessakayez@aim.com'
            %li
              %a{href: "/quotes/new"} New Quote
          - else
            %li
              %a{href: "/favorites"} Favorites
          %li
            = link_to 'Logout', '/users/sign_out', method: 'DELETE'
        - else
          %li
            %a{href: "/favorites"} Login
          %li
            %a{href: "/quotes/new"} Admin
          -# %li
          -#   %a{href: "#portfolio"} Portfolio
          -# %li
          -#   %a{href: "#contact"} Contact
    / /Side Menu
    / Full Page Image Header Area
    #top.header
      .vert-text
        = yield
    / /Full Page Image Header Area
    / Intro
    #about.intro
      .container
        .row
          .col-md-6.col-md-offset-3.text-center
            %h2 Android
            %p.lead
              Get these quotes free on your android device, now updated and better than ever!!!
              %br
              = succeed "." do
                %a{href: "https://play.google.com/store/apps/details?id=nice.quotables.online&hl=en_GB", target: "_blank"} QUOTABLES
    -# / /Intro
    -# / Services
    -# #services.services
    -#   .container
    -#     .row
    -#       .col-md-4.col-md-offset-4.text-center
    -#         %h2 Our Services
    -#         %hr/
    -#     .row
    -#       .col-md-2.col-md-offset-2.text-center
    -#         .service-item
    -#           %i.service-icon.fa.fa-rocket
    -#           %h4 Spacecraft Repair
    -#           %p Did your navigation system shut down in the middle of that asteroid field? We can repair any dings and scrapes to your spacecraft!
    -#       .col-md-2.text-center
    -#         .service-item
    -#           %i.service-icon.fa.fa-magnet
    -#           %h4 Problem Solving
    -#           %p Need to know how magnets work? Our problem solving solutions team can help you identify problems and conduct exploratory research.
    -#       .col-md-2.text-center
    -#         .service-item
    -#           %i.service-icon.fa.fa-shield
    -#           %h4 Blacksmithing
    -#           %p Planning a time travel trip to the middle ages? Preserve the space time continuum by blending in with period accurate armor and weapons.
    -#       .col-md-2.text-center
    -#         .service-item
    -#           %i.service-icon.fa.fa-pencil
    -#           %h4 Pencil Sharpening
    -#           %p We've been voted the best pencil sharpening service for 10 consecutive years. If you have a pencil that feels dull, we'll get it sharp!
    -# / /Services
    -# / Callout
    -# .callout
    -#   .vert-text
    -#     %h1 A Dramatic Text Area
    -# / /Callout
    -# / Portfolio
    -# #portfolio.portfolio
    -#   .container
    -#     .row
    -#       .col-md-4.col-md-offset-4.text-center
    -#         %h2 Our Work
    -#         %hr/
    -#     .row
    -#       .col-md-4.col-md-offset-2.text-center
    -#         .portfolio-item
    -#           %a{href: "#"}
    -#             %img.img-portfolio.img-responsive{src: "img/portfolio-1.jpg"}/
    -#           %h4 Cityscape
    -#       .col-md-4.text-center
    -#         .portfolio-item
    -#           %a{href: "#"}
    -#             %img.img-portfolio.img-responsive{src: "img/portfolio-2.jpg"}/
    -#           %h4 Is That On Fire?
    -#     .row
    -#       .col-md-4.col-md-offset-2.text-center
    -#         .portfolio-item
    -#           %a{href: "#"}
    -#             %img.img-portfolio.img-responsive{src: "img/portfolio-3.jpg"}/
    -#           %h4 Stop Sign
    -#       .col-md-4.text-center
    -#         .portfolio-item
    -#           %a{href: "#"}
    -#             %img.img-portfolio.img-responsive{src: "img/portfolio-4.jpg"}/
    -#           %h4 Narrow Focus
    -# / /Portfolio
    -# / Call to Action
    -# .call-to-action
    -#   .container
    -#     .row
    -#       .col-md-6.col-md-offset-3.text-center
    -#         %h3 The buttons below are impossible to resist.
    -#         %a.btn.btn-lg.btn-default{href: "#"} Click Me!
    -#         %a.btn.btn-lg.btn-primary{href: "#"} Look at Me!
    -# / /Call to Action
    -# / Map
    -# #contact.map
    -#   %iframe{frameborder: "0", height: "100%", marginheight: "0", marginwidth: "0", scrolling: "no", src: "https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&aq=0&oq=twitter&sll=28.659344,-81.187888&sspn=0.128789,0.264187&ie=UTF8&hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&t=m&z=15&iwloc=A&output=embed", width: "100%"}
    -#   %br/
    -#   %small
    -#     %a{href: "https://maps.google.com/maps?f=q&source=embed&hl=en&geocode=&q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&aq=0&oq=twitter&sll=28.659344,-81.187888&sspn=0.128789,0.264187&ie=UTF8&hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&t=m&z=15&iwloc=A"}
    -# / /Map
    -# / Footer
    -# %footer
    -#   .container
    -#     .row
    -#       .col-md-6.col-md-offset-3.text-center
    -#         %ul.list-inline
    -#           %li
    -#             %i.fa.fa-facebook.fa-3x
    -#           %li
    -#             %i.fa.fa-twitter.fa-3x
    -#           %li
    -#             %i.fa.fa-dribbble.fa-3x
    -#         .top-scroll
    -#           %a{href: "#top"}
    -#             %i.fa.fa-circle-arrow-up.scroll.fa-4x
    -#         %hr/
    -#         %p Copyright © Company 2013
    / /Footer
    / JavaScript
    -# %script{src: "js/jquery-1.10.2.js"}
    %script{src: "js/bootstrap.js"}
    / Custom JavaScript for the Side Menu and Smooth Scrolling
    :javascript
      $("#menu-close").click(function(e) {
          e.preventDefault();
          $("#sidebar-wrapper").toggleClass("active");
      });
    :javascript
      $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#sidebar-wrapper").toggleClass("active");
      });
    :javascript
      $(function() {
          $('a[href*=#]:not([href=#])').click(function() {
              if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                  var target = $(this.hash);
                  target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                  if (target.length) {
                      $('html,body').animate({
                          scrollTop: target.offset().top
                      }, 1000);
                      return false;
                  }
              }
          });
      });

app/views/quotes/_form.html.haml
= form_for(@quote) do |f|
  - if @quote.errors.any?
    #error_explanation
      %h2
        = pluralize(@quote.errors.count, "error")
        prohibited this quote from being saved:
      %ul
        - @quote.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :content
    %br/
    = f.text_area :content, rows: 20, style: 'width:500px'
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .actions
    = f.submit

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/edit.html.haml
%h1 Editing quote
= render 'form'
= link_to 'Show', @quote
|
\#{link_to 'Back', quotes_path}

app/views/quotes/index.html.haml
%b{style: "color:green"}= flash[:notice]
= simple_format @quote.content, class: 'cursive'
%h3
  %em From:
  = @quote.author
%br
%br
= form_for Favorite.new do |f|
  %a.btn.btn-default.btn-lg{href: "/quotes?id=#{@quote.prev.id}"} Previous
  = f.hidden_field :quote_id, value: @quote.id
  = f.submit 'Favorite', class: "btn btn-default btn-lg", method: 'POST'
  %a.btn.btn-default.btn-lg{href: "/quotes?id=#{@quote.next.id}"} Next

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/new.html.haml
%h1 New quote
= render 'form'
= link_to 'Back', quotes_path

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @quote.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @quote.author %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.haml
%p#notice= notice
%p
  %strong Content:
  = @quote.content
%p
  %strong Author:
  = @quote.author
= link_to 'Edit', edit_quote_path(@quote)
|
\#{link_to 'Back', quotes_path}